name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # 添加手动触发器
    inputs:
      sync:
        description: 'Sync with upstream manually'
        default: 'true'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Fetch upstream changes
        run: git fetch upstream
        continue-on-error: true
      
      - name: Check out main branch
        run: git checkout main
      
      - name: Merge upstream changes
        run: git merge upstream/main --ff-only
        continue-on-error: true
      
      - name: Push changes to fork
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
